const CONFIG = {
    catalog: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRIumwZulbMAuesmG69DB8Y1bx2Y-NQXfyG7_m1-rdpZ-SoOxM0JyZtnj0_eV_K4t4drULTwV44nE5Y/pub?gid=0&single=true&output=csv",
    formURL: "https://docs.google.com/forms/d/e/1FAIpQLSend7KPNCjTNP1d-B3zd-wvhZAVXLS3P7341yN88fm3d7D4Jw/formResponse",
    wa: "393667540018",
    freeShippingThreshold: 120,
    shippingCostIT: 13,
    shippingCostEU: 50
};

const TEXT = {
    it: {
        heroTitle: "L'Oro del Cilento, a casa tua",
        heroSubtitle: "Eccellenza gastronomica dal cuore del Parco Nazionale del Cilento. Prodotti autentici, sapori genuini, tradizione e qualità.",
        heroCta: "Scopri i Prodotti",
        heroSecondary: "Contattaci",
        heroTag: "Qualità Premium",
        heroFeature1: "Spedizione Rapida",
        heroFeature2: "100% Naturale",
        heroFeature3: "Pagamento Sicuro",
        heroBadge: "Spedizione Gratuita sopra €120",
        searchPlaceholder: "Cerca prodotti...",
        searchEmpty: "Nessun prodotto trovato",
        searchEmptySub: "Prova con una diversa parola chiave",
        featured: "In Evidenza",
        featuredSubtitle: "I prodotti più amati dai nostri clienti",
        allProducts: "Tutti i Prodotti",
        allProductsSubtitle: "Esplora la nostra selezione di eccellenze cilentane",
        categories: "Categorie",
        departments: "Dipartimenti",
        addToCart: "Aggiungi",
        addToCartFull: "Aggiungi al Carrello",
        viewDetails: "Dettagli",
        quickView: "Veloce",
        inStock: "Disponibile",
        lowStock: "Ultimi pezzi",
        outOfStock: "Esaurito",
        newBadge: "Nuovo",
        saleBadge: "Sconto",
        pricePer: "al",
        cartTitle: "Il Tuo Carrello",
        cartEmpty: "Il carrello è vuoto",
        cartEmptyMsg: "Aggiungi prodotti deliziosi per iniziare!",
        startShopping: "Inizia a Comprare",
        subtotal: "Subtotale",
        shipping: "Spedizione",
        total: "Totale",
        freeShipping: "Spedizione gratuita",
        freeShippingProgress: "Aggiungi ancora {amount} per la spedizione gratuita",
        freeShippingReached: "Hai ottenuto la spedizione gratuita!",
        promoCode: "Codice Promo",
        applyPromo: "Applica",
        promoApplied: "Applicato ✓",
        promoInvalid: "Codice non valido",
        checkout: "Procedi all'Ordine",
        checkoutFull: "Procedi all'Ordine",
        continueShopping: "Continua lo Shopping",
        clearCart: "Svuota Carrello",
        clearCartConfirm: "Sei sicuro di voler svuotare il carrello?",
        removeItem: "Rimuovi",
        quantity: "Quantità",
        maxQty: "Max disponibili",
        checkoutTitle: "Completa l'Ordine",
        checkoutSubtitle: "Inserisci i dati di spedizione",
        fullName: "Nome e Cognome",
        email: "Email",
        phone: "Telefono",
        address: "Indirizzo Completo",
        addressPlaceholder: "Via Roma 1, 00100 Città (CAP)",
        city: "Città",
        cap: "CAP",
        country: "Paese",
        countryIT: "Italia",
        countryEU: "Europa (UE)",
        notes: "Note aggiuntive",
        notesPlaceholder: "Istruzioni speciali per la consegna...",
        confirmOrder: "Conferma e Ordina",
        cancel: "Annulla",
        successTitle: "Grazie!",
        successMessage: "Il tuo ordine è stato confermato con successo",
        successSubMessage: "Riceverai presto una conferma via email e WhatsApp",
        orderId: "Numero Ordine",
        backToSite: "Torna al Sito",
        stockAlert: "Hai raggiunto la disponibilità massima",
        cartEmptyAlert: "Il carrello è vuoto",
        orderError: "Si è verificato un errore. Riprova.",
        orderSuccess: "Ordine inviato con successo!",
        loading: "Caricamento...",
        wishlist: "Preferiti",
        wishlistAdded: "Aggiunto ai preferiti",
        wishlistRemoved: "Rimosso dai preferiti",
        footerTagline: "Eccellenza gastronomica dal cuore del Cilento",
        footerShop: "Negozio",
        footerCompany: "Azienda",
        footerSupport: "Assistenza",
        footerContact: "Contatti",
        footerAbout: "Chi Siamo",
        footerTerms: "Termini e Condizioni",
        footerPrivacy: "Privacy Policy",
        footerReturns: "Resi e Rimborsi",
        footerShipping: "Spedizioni",
        footerFAQ: "FAQ",
        footerCopyright: "© 2026 Gruppo Gizzi. Tutti i diritti riservati.",
        footerPhone: "+39 335 806 0715",
        footerEmail: "info@gruppogizzi.it",
        footerAddress: "Cilento, Italia",
        gdprTitle: "Privacy & Cookie Policy",
        gdprText: "Utilizziamo cookie e tecnologie simili per migliorare la tua esperienza di navigazione, analizzare il traffico e personalizzare contenuti e annunci. Continuando, accetti la nostra Cookie Policy.",
        accept: "Accetta Tutto",
        reject: "Rifiuta",
        toastSuccess: "Successo",
        toastError: "Errore",
        toastWarning: "Attenzione",
        close: "Chiudi",
        menu: "Menu",
        open: "Apri",
        themeLight: "Tema Chiaro",
        themeDark: "Tema Scuro",
        viewAll: "Vedi Tutti",
        readMore: "Leggi di più",
        showLess: "Mostra meno",
        next: "Successivo",
        previous: "Precedente",
        page: "Pagina",
        of: "di",
        results: "risultati",
        noResults: "Nessun risultato",
        sortBy: "Ordina per",
        sortByDefault: "Default",
        sortByPriceLow: "Prezzo: Basso → Alto",
        sortByPriceHigh: "Prezzo: Alto → Basso",
        sortByNew: "Novità",
        sortByPopular: "Popolari",
        filter: "Filtra",
        filters: "Filtri",
        clearFilters: "Cancella Filtri",
        applyFilters: "Applica Filtri",
        categoryAll: "Tutte le Categorie",
        priceRange: "Fascia di Prezzo",
        rating: "Valutazione",
        brand: "Marchio",
        size: "Taglia",
        color: "Colore",
        material: "Materiale",
        availability: "Disponibilità",
        available: "Disponibile",
        unavailable: "Non disponibile",
        onSale: "In Offerta",
        newArrivals: "Nuovi Arrivi",
        bestSellers: "Più Venduti",
        recommended: "Consigliati",
        relatedProducts: "Prodotti Correlati",
        youMayAlsoLike: "Potrebbe piacerti anche",
        recentlyViewed: "Visti di recente",
        compare: "Confronta",
        compareProducts: "Confronta Prodotti",
        removeCompare: "Rimuovi dal confronto",
        maxCompareReached: "Puoi confrontare massimo 4 prodotti",
        share: "Condividi",
        shareOnFacebook: "Condividi su Facebook",
        shareOnTwitter: "Condividi su Twitter",
        shareOnWhatsApp: "Condividi su WhatsApp",
        copyLink: "Copia Link",
        linkCopied: "Link copiato negli appunti",
        reportProduct: "Segnala Prodotto",
        reportSuccess: "Prodotto segnalato con successo",
        askQuestion: "Fai una Domanda",
        submitQuestion: "Invia Domanda",
        questionSuccess: "Domanda inviata con successo",
        productReviews: "Recensioni Prodotto",
        writeReview: "Scrivi una Recensione",
        reviewTitle: "Titolo",
        reviewContent: "La tua recensione",
        ratingRequired: "Valutazione richiesta",
        reviewSuccess: "Recensione inviata con successo",
        verifiedPurchase: "Acquisto Verificato",
        helpful: "Utile",
        notHelpful: "Non utile",
        reportReview: "Segnala recensione",
        cart: "Carrello",
        sectionFeature1Title: "100% Naturale",
        sectionFeature1Desc: "Prodotti autentici senza conservanti o additivi artificiali",
        sectionFeature2Title: "Origine Cilento",
        sectionFeature2Desc: "Dal cuore del Parco Nazionale, direttamente a casa tua",
        sectionFeature3Title: "Qualità Premium",
        sectionFeature3Desc: "Selezione accurata dei migliori prodotti locali"
    },
    en: {
        heroTitle: "Cilento's Gold at Home",
        heroSubtitle: "Gastronomic excellence from the heart of Cilento National Park. Authentic products, genuine flavors, tradition and quality.",
        heroCta: "Discover Products",
        heroSecondary: "Contact Us",
        heroTag: "Premium Quality",
        heroFeature1: "Fast Shipping",
        heroFeature2: "100% Natural",
        heroFeature3: "Secure Payment",
        heroBadge: "Free Shipping on orders over €120",
        searchPlaceholder: "Search products...",
        searchEmpty: "No products found",
        searchEmptySub: "Try a different keyword",
        featured: "Featured",
        featuredSubtitle: "Most loved products by our customers",
        allProducts: "All Products",
        allProductsSubtitle: "Explore our selection of Cilento excellences",
        categories: "Categories",
        departments: "Departments",
        addToCart: "Add to Cart",
        addToCartFull: "Add to Cart",
        viewDetails: "Details",
        quickView: "Quick View",
        inStock: "In Stock",
        lowStock: "Low Stock",
        outOfStock: "Out of Stock",
        newBadge: "New",
        saleBadge: "Sale",
        pricePer: "per",
        cartTitle: "Your Cart",
        cartEmpty: "Your cart is empty",
        cartEmptyMsg: "Add delicious products to get started!",
        startShopping: "Start Shopping",
        subtotal: "Subtotal",
        shipping: "Shipping",
        total: "Total",
        freeShipping: "Free shipping",
        freeShippingProgress: "Add {amount} more for free shipping",
        freeShippingReached: "You've got free shipping!",
        promoCode: "Promo Code",
        applyPromo: "Apply",
        promoApplied: "Applied ✓",
        promoInvalid: "Invalid code",
        checkout: "Checkout",
        checkoutFull: "Proceed to Checkout",
        continueShopping: "Continue Shopping",
        clearCart: "Clear Cart",
        clearCartConfirm: "Are you sure you want to clear your cart?",
        removeItem: "Remove",
        quantity: "Quantity",
        maxQty: "Max available",
        checkoutTitle: "Complete Order",
        checkoutSubtitle: "Enter shipping details",
        fullName: "Full Name",
        email: "Email",
        phone: "Phone",
        address: "Complete Address",
        addressPlaceholder: "123 Main Street, City, ZIP",
        city: "City",
        cap: "Postal Code",
        country: "Country",
        countryIT: "Italy",
        countryEU: "Europe (EU)",
        notes: "Additional Notes",
        notesPlaceholder: "Special delivery instructions...",
        confirmOrder: "Confirm Order",
        cancel: "Cancel",
        successTitle: "Thank You!",
        successMessage: "Your order has been confirmed successfully",
        successSubMessage: "You will receive confirmation via email and WhatsApp soon",
        orderId: "Order Number",
        backToSite: "Back to Site",
        stockAlert: "You've reached maximum availability",
        cartEmptyAlert: "Cart is empty",
        orderError: "An error occurred. Please try again.",
        orderSuccess: "Order sent successfully!",
        loading: "Loading...",
        wishlist: "Wishlist",
        wishlistAdded: "Added to wishlist",
        wishlistRemoved: "Removed from wishlist",
        footerTagline: "Gastronomic excellence from the heart of Cilento",
        footerShop: "Shop",
        footerCompany: "Company",
        footerSupport: "Support",
        footerContact: "Contact",
        footerAbout: "About Us",
        footerTerms: "Terms & Conditions",
        footerPrivacy: "Privacy Policy",
        footerReturns: "Returns & Refunds",
        footerShipping: "Shipping",
        footerFAQ: "FAQ",
        footerCopyright: "© 2026 Gruppo Gizzi. All rights reserved.",
        footerPhone: "+39 335 806 0715",
        footerEmail: "info@gruppogizzi.it",
        footerAddress: "Cilento, Italy",
        gdprTitle: "Privacy & Cookie Policy",
        gdprText: "We use cookies and similar technologies to improve your browsing experience, analyze traffic and personalize content and ads. By continuing, you accept our Cookie Policy.",
        accept: "Accept All",
        reject: "Reject",
        toastSuccess: "Success",
        toastError: "Error",
        toastWarning: "Warning",
        close: "Close",
        menu: "Menu",
        open: "Open",
        themeLight: "Light Theme",
        themeDark: "Dark Theme",
        viewAll: "View All",
        readMore: "Read More",
        showLess: "Show Less",
        next: "Next",
        previous: "Previous",
        page: "Page",
        of: "of",
        results: "results",
        noResults: "No results",
        sortBy: "Sort by",
        sortByDefault: "Default",
        sortByPriceLow: "Price: Low to High",
        sortByPriceHigh: "Price: High to Low",
        sortByNew: "Newest",
        sortByPopular: "Popular",
        filter: "Filter",
        filters: "Filters",
        clearFilters: "Clear Filters",
        applyFilters: "Apply Filters",
        categoryAll: "All Categories",
        priceRange: "Price Range",
        rating: "Rating",
        brand: "Brand",
        size: "Size",
        color: "Color",
        material: "Material",
        availability: "Availability",
        available: "Available",
        unavailable: "Unavailable",
        onSale: "On Sale",
        newArrivals: "New Arrivals",
        bestSellers: "Best Sellers",
        recommended: "Recommended",
        relatedProducts: "Related Products",
        youMayAlsoLike: "You May Also Like",
        recentlyViewed: "Recently Viewed",
        compare: "Compare",
        compareProducts: "Compare Products",
        removeCompare: "Remove from comparison",
        maxCompareReached: "You can compare up to 4 products",
        share: "Share",
        shareOnFacebook: "Share on Facebook",
        shareOnTwitter: "Share on Twitter",
        shareOnWhatsApp: "Share on WhatsApp",
        copyLink: "Copy Link",
        linkCopied: "Link copied to clipboard",
        reportProduct: "Report Product",
        reportSuccess: "Product reported successfully",
        askQuestion: "Ask a Question",
        submitQuestion: "Submit Question",
        questionSuccess: "Question submitted successfully",
        productReviews: "Product Reviews",
        writeReview: "Write a Review",
        reviewTitle: "Title",
        reviewContent: "Your review",
        ratingRequired: "Rating required",
        reviewSuccess: "Review submitted successfully",
        verifiedPurchase: "Verified Purchase",
        helpful: "Helpful",
        notHelpful: "Not Helpful",
        reportReview: "Report review",
        cart: "Cart"
    },
    de: {
        heroTitle: "Cilento Gold bei Ihnen zu Hause",
        heroSubtitle: "Kulinarische Exzellenz aus dem Herzen des Nationalparks Cilento. Authentische Produkte, echte Aromen, Tradition und Qualität.",
        heroCta: "Entdecken Sie Produkte",
        heroSecondary: "Kontaktieren Sie uns",
        heroTag: "Premium Qualität",
        heroFeature1: "Schneller Versand",
        heroFeature2: "100% Natürliche",
        heroFeature3: "Sichere Zahlung",
        heroBadge: "Kostenloser Versand ab €120",
        searchPlaceholder: "Produkte suchen...",
        searchEmpty: "Keine Produkte gefunden",
        searchEmptySub: "Versuchen Sie ein anderes Schlagwort",
        featured: "Highlights",
        featuredSubtitle: "Die beliebtesten Produkte unserer Kunden",
        allProducts: "Alle Produkte",
        allProductsSubtitle: "Entdecken Sie unsere Auswahl von Cilento-Spitzenprodukten",
        categories: "Kategorien",
        departments: "Abteilungen",
        addToCart: "In den Warenkorb",
        addToCartFull: "In den Warenkorb",
        viewDetails: "Details",
        quickView: "Schnellansicht",
        inStock: "Verfügbar",
        lowStock: "Wenig Vorrat",
        outOfStock: "Ausverkauft",
        newBadge: "Neu",
        saleBadge: "Angebot",
        pricePer: "pro",
        cartTitle: "Ihr Warenkorb",
        cartEmpty: "Ihr Warenkorb ist leer",
        cartEmptyMsg: "Fügen Sie köstliche Produkte hinzu!",
        startShopping: "Einkaufen beginnen",
        subtotal: "Zwischensumme",
        shipping: "Versand",
        total: "Gesamt",
        freeShipping: "Kostenloser Versand",
        freeShippingProgress: "Fügen Sie noch {amount} für kostenlosen Versand hinzu",
        freeShippingReached: "Sie haben kostenlosen Versand erhalten!",
        promoCode: "Promo-Code",
        applyPromo: "Anwenden",
        promoApplied: "Angewendet ✓",
        promoInvalid: "Ungültiger Code",
        checkout: "Zur Kasse",
        checkoutFull: "Zur Kasse gehen",
        continueShopping: "Einkaufen fortsetzen",
        clearCart: "Warenkorb leeren",
        clearCartConfirm: "Sind Sie sicher, dass Sie den Warenkorb leeren möchten?",
        removeItem: "Entfernen",
        quantity: "Menge",
        maxQty: "Maximal verfügbar",
        checkoutTitle: "Bestellung abschließen",
        checkoutSubtitle: "Versanddetails eingeben",
        fullName: "Vollständiger Name",
        email: "E-Mail",
        phone: "Telefon",
        address: "Vollständige Adresse",
        addressPlaceholder: "Musterstraße 1, 12345 Stadt",
        city: "Stadt",
        cap: "Postleitzahl",
        country: "Land",
        countryIT: "Italien",
        countryEU: "Europa (EU)",
        notes: "Zusätzliche Hinweise",
        notesPlaceholder: "Besondere Lieferhinweise...",
        confirmOrder: "Bestellung bestätigen",
        cancel: "Abbrechen",
        successTitle: "Danke!",
        successMessage: "Ihre Bestellung wurde erfolgreich bestätigt",
        successSubMessage: "Sie erhalten bald eine Bestätigung per E-Mail und WhatsApp",
        orderId: "Bestellnummer",
        backToSite: "Zurück zur Website",
        stockAlert: "Sie haben die maximale Verfügbarkeit erreicht",
        cartEmptyAlert: "Warenkorb ist leer",
        orderError: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
        orderSuccess: "Bestellung erfolgreich gesendet!",
        loading: "Wird geladen...",
        wishlist: "Wunschliste",
        wishlistAdded: "Zur Wunschliste hinzugefügt",
        wishlistRemoved: "Von Wunschliste entfernt",
        footerTagline: "Kulinarische Exzellenz aus dem Herzen von Cilento",
        footerShop: "Shop",
        footerCompany: "Unternehmen",
        footerSupport: "Support",
        footerContact: "Kontakt",
        footerAbout: "Über uns",
        footerTerms: "AGB",
        footerPrivacy: "Datenschutz",
        footerReturns: "Rücksendungen",
        footerShipping: "Versand",
        footerFAQ: "FAQ",
        footerCopyright: "© 2026 Gruppo Gizzi. Alle Rechte vorbehalten.",
        footerPhone: "+39 335 806 0715",
        footerEmail: "info@gruppogizzi.it",
        footerAddress: "Cilento, Italien",
        gdprTitle: "Datenschutz & Cookie-Richtlinie",
        gdprText: "Wir verwenden Cookies und ähnliche Technologien, um Ihr Surferlebnis zu verbessern, den Verkehr zu analysieren und Inhalte und Anzeigen zu personalisieren. Durch Fortfahren akzeptieren Sie unsere Cookie-Richtlinie.",
        accept: "Alle akzeptieren",
        reject: "Ablehnen",
        toastSuccess: "Erfolg",
        toastError: "Fehler",
        toastWarning: "Warnung",
        close: "Schließen",
        menu: "Menü",
        open: "Öffnen",
        themeLight: "Helles Thema",
        themeDark: "Dunkles Thema",
        viewAll: "Alle anzeigen",
        readMore: "Mehr lesen",
        showLess: "Weniger anzeigen",
        next: "Weiter",
        previous: "Zurück",
        page: "Seite",
        of: "von",
        results: "Ergebnisse",
        noResults: "Keine Ergebnisse",
        sortBy: "Sortieren nach",
        sortByDefault: "Standard",
        sortByPriceLow: "Preis: Niedrig bis Hoch",
        sortByPriceHigh: "Preis: Hoch bis Niedrig",
        sortByNew: "Neueste",
        sortByPopular: "Beliebt",
        filter: "Filter",
        filters: "Filter",
        clearFilters: "Filter löschen",
        applyFilters: "Filter anwenden",
        categoryAll: "Alle Kategorien",
        priceRange: "Preisbereich",
        rating: "Bewertung",
        brand: "Marke",
        size: "Größe",
        color: "Farbe",
        material: "Material",
        availability: "Verfügbarkeit",
        available: "Verfügbar",
        unavailable: "Nicht verfügbar",
        onSale: "Im Angebot",
        newArrivals: "Neuheiten",
        bestSellers: "Bestseller",
        recommended: "Empfohlen",
        relatedProducts: "Verwandte Produkte",
        youMayAlsoLike: "Das könnte Ihnen auch gefallen",
        recentlyViewed: "Kürzlich angesehen",
        compare: "Vergleichen",
        compareProducts: "Produkte vergleichen",
        removeCompare: "Aus Vergleich entfernen",
        maxCompareReached: "Sie können bis zu 4 Produkte vergleichen",
        share: "Teilen",
        shareOnFacebook: "Auf Facebook teilen",
        shareOnTwitter: "Auf Twitter teilen",
        shareOnWhatsApp: "Auf WhatsApp teilen",
        copyLink: "Link kopieren",
        linkCopied: "Link in die Zwischenablage kopiert",
        reportProduct: "Produkt melden",
        reportSuccess: "Produkt erfolgreich gemeldet",
        askQuestion: "Frage stellen",
        submitQuestion: "Frage absenden",
        questionSuccess: "Frage erfolgreich gesendet",
        productReviews: "Produktbewertungen",
        writeReview: "Bewertung schreiben",
        reviewTitle: "Titel",
        reviewContent: "Ihre Bewertung",
        ratingRequired: "Bewertung erforderlich",
        reviewSuccess: "Bewertung erfolgreich gesendet",
        verifiedPurchase: "Verifizierter Kauf",
        helpful: "Hilfreich",
        notHelpful: "Nicht hilfreich",
        reportReview: "Bewertung melden",
        cart: "Warenkorb"
    },
    hu: {
        heroTitle: "Cilento Aranya otthonában",
        heroSubtitle: "Gasztronómiai élmény a Nemzeti Park szívéből. Hiteles termékek, igazi ízek, hagyomány és minőség.",
        heroCta: "Fedezze fel a termékeket",
        heroSecondary: "Lépjen velünk kapcsolatba",
        heroTag: "Prémium Minőség",
        heroFeature1: "Gyors Szállítás",
        heroFeature2: "100% Természetes",
        heroFeature3: "Biztonságos Fizetés",
        heroBadge: "Ingyenes szállítás €120 felett",
        searchPlaceholder: "Termékek keresése...",
        searchEmpty: "Nem találtunk terméket",
        searchEmptySub: "Próbáljon másik kulcsszót",
        featured: "Kiemelt",
        featuredSubtitle: "Ügyfeleink legkedveltebb termékei",
        allProducts: "Összes termék",
        allProductsSubtitle: "Fedezze fel Cilento kiválóságainkat",
        categories: "Kategóriák",
        departments: "Részlegek",
        addToCart: "Kosárba",
        addToCartFull: "Kosárba tesz",
        viewDetails: "Részletek",
        quickView: "Gyors nézet",
        inStock: "Elérhető",
        lowStock: "Készleten",
        outOfStock: "Elfogyott",
        newBadge: "Új",
        saleBadge: "Akció",
        pricePer: "egy",
        cartTitle: "Kosár",
        cartEmpty: "A kosár üres",
        cartEmptyMsg: "Adjon hozzá finom termékeket!",
        startShopping: "Vásárlás kezdése",
        subtotal: "Részösszeg",
        shipping: "Szállítás",
        total: "Összesen",
        freeShipping: "Ingyenes szállítás",
        freeShippingProgress: "Vegyen hozzá még {amount} az ingyenes szállításhoz",
        freeShippingReached: "Megkapta az ingyenes szállítást!",
        promoCode: "Promó kód",
        applyPromo: "Alkalmaz",
        promoApplied: "Alkalmazva ✓",
        promoInvalid: "Érvénytelen kód",
        checkout: "Pénztár",
        checkoutFull: "Pénztárhoz",
        continueShopping: "Vásárlás folytatása",
        clearCart: "Kosár ürítése",
        clearCartConfirm: "Biztosan ki akarja üríteni a kosarat?",
        removeItem: "Eltávolítás",
        quantity: "Mennyiség",
        maxQty: "Max. elérhető",
        checkoutTitle: "Rendelés befejezése",
        checkoutSubtitle: "Szállítási adatok megadása",
        fullName: "Teljes név",
        email: "E-mail",
        phone: "Telefon",
        address: "Teljes cím",
        addressPlaceholder: "Fő utca 1, 12345 Város",
        city: "Város",
        cap: "Irányítószám",
        country: "Ország",
        countryIT: "Olaszország",
        countryEU: "Európa (EU)",
        notes: "További megjegyzések",
        notesPlaceholder: "Speciális szállítási utasítások...",
        confirmOrder: "Rendelés megerősítése",
        cancel: "Mégse",
        successTitle: "Köszönjük!",
        successMessage: "Rendelése sikeresen megerősítve",
        successSubMessage: "Hamárosan kap megerősítést e-mailben és WhatsAppon",
        orderId: "Rendelésszám",
        backToSite: "Vissza a weboldalra",
        stockAlert: "Elérte a maximális mennyiséget",
        cartEmptyAlert: "A kosár üres",
        orderError: "Hiba történt. Próbálja újra.",
        orderSuccess: "Rendelés sikeresen elküldve!",
        loading: "Betöltés...",
        wishlist: "Kedvencek",
        wishlistAdded: "Hozzáadva a kedvencekhez",
        wishlistRemoved: "Eltávolítva a kedvencekből",
        footerTagline: "Gasztronómiai élmény a Nemzeti Park szívéből",
        footerShop: "Bolt",
        footerCompany: "Cég",
        footerSupport: "Támogatás",
        footerContact: "Kapcsolat",
        footerAbout: "Rólunk",
        footerTerms: "Általános Szerződési Feltételek",
        footerPrivacy: "Adatvédelmi Szabályzat",
        footerReturns: "Visszaküldés",
        footerShipping: "Szállítás",
        footerFAQ: "GYIK",
        footerCopyright: "© 2026 Gruppo Gizzi. Minden jog fenntartva.",
        footerPhone: "+39 335 806 0715",
        footerEmail: "info@gruppogizzi.it",
        footerAddress: "Cilento, Olaszország",
        gdprTitle: "Adatvédelem és Cookie Irányelvek",
        gdprText: "Sütiket és hasonló technológiákat használunk a böngészési élmény javítására, a forgalom elemzésére és a tartalmak és hirdetések személyre szabására. A folytatással elfogadja Cookie Irányelveinket.",
        accept: "Összes elfogadása",
        reject: "Elutasítás",
        toastSuccess: "Siker",
        toastError: "Hiba",
        toastWarning: "Figyelem",
        close: "Bezárás",
        menu: "Menü",
        open: "Megnyitás",
        themeLight: "Világos téma",
        themeDark: "Sötét téma",
        viewAll: "Összes megtekintése",
        readMore: "Tovább olvasás",
        showLess: "Kevesebb megjelenítése",
        next: "Következő",
        previous: "Előző",
        page: "Oldal",
        of: "/",
        results: "eredmény",
        noResults: "Nincs találat",
        sortBy: "Rendezés",
        sortByDefault: "Alapértelmezett",
        sortByPriceLow: "Ár: Növekvő",
        sortByPriceHigh: "Ár: Csökkenő",
        sortByNew: "Legújabb",
        sortByPopular: "Népszerű",
        filter: "Szűrő",
        filters: "Szűrők",
        clearFilters: "Szűrők törlése",
        applyFilters: "Szűrők alkalmazása",
        categoryAll: "Összes kategória",
        priceRange: "Ártartomány",
        rating: "Értékelés",
        brand: "Márka",
        size: "Méret",
        color: "Szín",
        material: "Anyag",
        availability: "Elérhetőség",
        available: "Elérhető",
        unavailable: "Nem elérhető",
        onSale: "Akciós",
        newArrivals: "Újdonságok",
        bestSellers: "Legjobban fogyó",
        recommended: "Ajánlott",
        relatedProducts: "Kapcsolódó termékek",
        youMayAlsoLike: "Ez is tetszhet",
        recentlyViewed: "Nemrég megtekintett",
        compare: "Összehasonlítás",
        compareProducts: "Termékek összehasonlítása",
        removeCompare: "Eltávolítás az összehasonlításból",
        maxCompareReached: "Legfeljebb 4 terméket hasonlíthat össze",
        share: "Megosztás",
        shareOnFacebook: "Megosztás Facebookon",
        shareOnTwitter: "Megosztás Twitteren",
        shareOnWhatsApp: "Megosztás WhatsAppon",
        copyLink: "Link másolása",
        linkCopied: "Link a vágólapra másolva",
        reportProduct: "Termék jelentése",
        reportSuccess: "Termék sikeresen jelentve",
        askQuestion: "Kérdés feltevése",
        submitQuestion: "Kérdés beküldése",
        questionSuccess: "Kérdés sikeresen elküldve",
        productReviews: "Termékértékelések",
        writeReview: "Értékelés írása",
        reviewTitle: "Cím",
        reviewContent: "Értékelése",
        ratingRequired: "Értékelés szükséges",
        reviewSuccess: "Értékelés sikeresen elküldve",
        verifiedPurchase: "Ellenőrzött vásárlás",
        helpful: "Hasznos",
        notHelpful: "Nem hasznos",
        reportReview: "Értékelés jelentése",
        cart: "Kosár",
        sectionFeature1Title: "100% Natural",
        sectionFeature1Desc: "Authentic products without preservatives or artificial additives",
        sectionFeature2Title: "Cilento Origin",
        sectionFeature2Desc: "From the heart of the National Park, straight to your door",
        sectionFeature3Title: "Premium Quality",
        sectionFeature3Desc: "Careful selection of the best local products"
    },
    de: {
        heroTitle: "Cilento Gold bei Ihnen zu Hause",
        heroSubtitle: "Kulinarische Exzellenz aus dem Herzen des Nationalparks Cilento. Authentische Produkte, echte Aromen, Tradition und Qualität.",
        heroCta: "Entdecken Sie Produkte",
        heroSecondary: "Kontaktieren Sie uns",
        heroTag: "Premium Qualität",
        heroFeature1: "Schneller Versand",
        heroFeature2: "100% Natürliche",
        heroFeature3: "Sichere Zahlung",
        heroBadge: "Kostenloser Versand ab €120",
        searchPlaceholder: "Produkte suchen...",
        searchEmpty: "Keine Produkte gefunden",
        searchEmptySub: "Versuchen Sie ein anderes Schlagwort",
        featured: "Highlights",
        featuredSubtitle: "Die beliebtesten Produkte unserer Kunden",
        allProducts: "Alle Produkte",
        allProductsSubtitle: "Entdecken Sie unsere Auswahl von Cilento-Spitzenprodukten",
        categories: "Kategorien",
        departments: "Abteilungen",
        addToCart: "In den Warenkorb",
        addToCartFull: "In den Warenkorb",
        viewDetails: "Details",
        quickView: "Schnellansicht",
        inStock: "Verfügbar",
        lowStock: "Wenig Vorrat",
        outOfStock: "Ausverkauft",
        newBadge: "Neu",
        saleBadge: "Angebot",
        pricePer: "pro",
        cartTitle: "Ihr Warenkorb",
        cartEmpty: "Ihr Warenkorb ist leer",
        cartEmptyMsg: "Fügen Sie köstliche Produkte hinzu!",
        startShopping: "Einkaufen beginnen",
        subtotal: "Zwischensumme",
        shipping: "Versand",
        total: "Gesamt",
        freeShipping: "Kostenloser Versand",
        freeShippingProgress: "Fügen Sie noch {amount} für kostenlosen Versand hinzu",
        freeShippingReached: "Sie haben kostenlosen Versand erhalten!",
        promoCode: "Promo-Code",
        applyPromo: "Anwenden",
        promoApplied: "Angewendet ✓",
        promoInvalid: "Ungültiger Code",
        checkout: "Zur Kasse",
        checkoutFull: "Zur Kasse gehen",
        continueShopping: "Einkaufen fortsetzen",
        clearCart: "Warenkorb leeren",
        clearCartConfirm: "Sind Sie sicher, dass Sie den Warenkorb leeren möchten?",
        removeItem: "Entfernen",
        quantity: "Menge",
        maxQty: "Maximal verfügbar",
        checkoutTitle: "Bestellung abschließen",
        checkoutSubtitle: "Versanddetails eingeben",
        fullName: "Vollständiger Name",
        email: "E-Mail",
        phone: "Telefon",
        address: "Vollständige Adresse",
        addressPlaceholder: "Musterstraße 1, 12345 Stadt",
        city: "Stadt",
        cap: "Postleitzahl",
        country: "Land",
        countryIT: "Italien",
        countryEU: "Europa (EU)",
        notes: "Zusätzliche Hinweise",
        notesPlaceholder: "Besondere Lieferhinweise...",
        confirmOrder: "Bestellung bestätigen",
        cancel: "Abbrechen",
        successTitle: "Danke!",
        successMessage: "Ihre Bestellung wurde erfolgreich bestätigt",
        successSubMessage: "Sie erhalten bald eine Bestätigung per E-Mail und WhatsApp",
        orderId: "Bestellnummer",
        backToSite: "Zurück zur Website",
        stockAlert: "Sie haben die maximale Verfügbarkeit erreicht",
        cartEmptyAlert: "Warenkorb ist leer",
        orderError: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
        orderSuccess: "Bestellung erfolgreich gesendet!",
        loading: "Wird geladen...",
        wishlist: "Wunschliste",
        wishlistAdded: "Zur Wunschliste hinzugefügt",
        wishlistRemoved: "Von Wunschliste entfernt",
        footerTagline: "Kulinarische Exzellenz aus dem Herzen von Cilento",
        footerShop: "Shop",
        footerCompany: "Unternehmen",
        footerSupport: "Support",
        footerContact: "Kontakt",
        footerAbout: "Über uns",
        footerTerms: "AGB",
        footerPrivacy: "Datenschutz",
        footerReturns: "Rücksendungen",
        footerShipping: "Versand",
        footerFAQ: "FAQ",
        footerCopyright: "© 2026 Gruppo Gizzi. Alle Rechte vorbehalten.",
        footerPhone: "+39 335 806 0715",
        footerEmail: "info@gruppogizzi.it",
        footerAddress: "Cilento, Italien",
        gdprTitle: "Datenschutz & Cookie-Richtlinie",
        gdprText: "Wir verwenden Cookies und ähnliche Technologien, um Ihr Surferlebnis zu verbessern, den Verkehr zu analysieren und Inhalte und Anzeigen zu personalisieren. Durch Fortfahren akzeptieren Sie unsere Cookie-Richtlinie.",
        accept: "Alle akzeptieren",
        reject: "Ablehnen",
        toastSuccess: "Erfolg",
        toastError: "Fehler",
        toastWarning: "Warnung",
        close: "Schließen",
        menu: "Menü",
        open: "Öffnen",
        themeLight: "Helles Thema",
        themeDark: "Dunkles Thema",
        viewAll: "Alle anzeigen",
        readMore: "Mehr lesen",
        showLess: "Weniger anzeigen",
        next: "Weiter",
        previous: "Zurück",
        page: "Seite",
        of: "von",
        results: "Ergebnisse",
        noResults: "Keine Ergebnisse",
        sortBy: "Sortieren nach",
        sortByDefault: "Standard",
        sortByPriceLow: "Preis: Niedrig bis Hoch",
        sortByPriceHigh: "Preis: Hoch bis Niedrig",
        sortByNew: "Neueste",
        sortByPopular: "Beliebt",
        filter: "Filter",
        filters: "Filter",
        clearFilters: "Filter löschen",
        applyFilters: "Filter anwenden",
        categoryAll: "Alle Kategorien",
        priceRange: "Preisbereich",
        rating: "Bewertung",
        brand: "Marke",
        size: "Größe",
        color: "Farbe",
        material: "Material",
        availability: "Verfügbarkeit",
        available: "Verfügbar",
        unavailable: "Nicht verfügbar",
        onSale: "Im Angebot",
        newArrivals: "Neuheiten",
        bestSellers: "Bestseller",
        recommended: "Empfohlen",
        relatedProducts: "Verwandte Produkte",
        youMayAlsoLike: "Das könnte Ihnen auch gefallen",
        recentlyViewed: "Kürzlich angesehen",
        compare: "Vergleichen",
        compareProducts: "Produkte vergleichen",
        removeCompare: "Aus Vergleich entfernen",
        maxCompareReached: "Sie können bis zu 4 Produkte vergleichen",
        share: "Teilen",
        shareOnFacebook: "Auf Facebook teilen",
        shareOnTwitter: "Auf Twitter teilen",
        shareOnWhatsApp: "Auf WhatsApp teilen",
        copyLink: "Link kopieren",
        linkCopied: "Link in die Zwischenablage kopiert",
        reportProduct: "Produkt melden",
        reportSuccess: "Produkt erfolgreich gemeldet",
        askQuestion: "Frage stellen",
        submitQuestion: "Frage absenden",
        questionSuccess: "Frage erfolgreich gesendet",
        productReviews: "Produktbewertungen",
        writeReview: "Bewertung schreiben",
        reviewTitle: "Titel",
        reviewContent: "Ihre Bewertung",
        ratingRequired: "Bewertung erforderlich",
        reviewSuccess: "Bewertung erfolgreich gesendet",
        verifiedPurchase: "Verifizierter Kauf",
        helpful: "Hilfreich",
        notHelpful: "Nicht hilfreich",
        reportReview: "Bewertung melden",
        cart: "Warenkorb",
        sectionFeature1Title: "100% Natürlich",
        sectionFeature1Desc: "Authentische Produkte ohne Konservierungsstoffe oder künstliche Zusätze",
        sectionFeature2Title: "Cilento Herkunft",
        sectionFeature2Desc: "Aus dem Herzen des Nationalparks direkt zu Ihnen nach Hause",
        sectionFeature3Title: "Premium Qualität",
        sectionFeature3Desc: "Sorgfältige Auswahl der besten lokalen Produkte"
    },
    hu: {
        heroTitle: "Cilento Aranya otthonában",
        heroSubtitle: "Gasztronómiai élmény a Nemzeti Park szívéből. Hiteles termékek, igazi ízek, hagyomány és minőség.",
        heroCta: "Fedezze fel a termékeket",
        heroSecondary: "Lépjen velünk kapcsolatba",
        heroTag: "Prémium Minőség",
        heroFeature1: "Gyors Szállítás",
        heroFeature2: "100% Természetes",
        heroFeature3: "Biztonságos Fizetés",
        heroBadge: "Ingyenes szállítás €120 felett",
        searchPlaceholder: "Termékek keresése...",
        searchEmpty: "Nem találtunk terméket",
        searchEmptySub: "Próbáljon másik kulcsszót",
        featured: "Kiemelt",
        featuredSubtitle: "Ügyfeleink legkedveltebb termékei",
        allProducts: "Összes termék",
        allProductsSubtitle: "Fedezze fel Cilento kiválóságainkat",
        categories: "Kategóriák",
        departments: "Részlegek",
        addToCart: "Kosárba",
        addToCartFull: "Kosárba tesz",
        viewDetails: "Részletek",
        quickView: "Gyors nézet",
        inStock: "Elérhető",
        lowStock: "Készleten",
        outOfStock: "Elfogyott",
        newBadge: "Új",
        saleBadge: "Akció",
        pricePer: "egy",
        cartTitle: "Kosár",
        cartEmpty: "A kosár üres",
        cartEmptyMsg: "Adjon hozzá finom termékeket!",
        startShopping: "Vásárlás kezdése",
        subtotal: "Részösszeg",
        shipping: "Szállítás",
        total: "Összesen",
        freeShipping: "Ingyenes szállítás",
        freeShippingProgress: "Vegyen hozzá még {amount} az ingyenes szállításhoz",
        freeShippingReached: "Megkapta az ingyenes szállítást!",
        promoCode: "Promó kód",
        applyPromo: "Alkalmaz",
        promoApplied: "Alkalmazva ✓",
        promoInvalid: "Érvénytelen kód",
        checkout: "Pénztár",
        checkoutFull: "Pénztárhoz",
        continueShopping: "Vásárlás folytatása",
        clearCart: "Kosár ürítése",
        clearCartConfirm: "Biztosan ki akarja üríteni a kosarat?",
        removeItem: "Eltávolítás",
        quantity: "Mennyiség",
        maxQty: "Max. elérhető",
        checkoutTitle: "Rendelés befejezése",
        checkoutSubtitle: "Szállítási adatok megadása",
        fullName: "Teljes név",
        email: "E-mail",
        phone: "Telefon",
        address: "Teljes cím",
        addressPlaceholder: "Fő utca 1, 12345 Város",
        city: "Város",
        cap: "Irányítószám",
        country: "Ország",
        countryIT: "Olaszország",
        countryEU: "Európa (EU)",
        notes: "További megjegyzések",
        notesPlaceholder: "Speciális szállítási utasítások...",
        confirmOrder: "Rendelés megerősítése",
        cancel: "Mégse",
        successTitle: "Köszönjük!",
        successMessage: "Rendelése sikeresen megerősítve",
        successSubMessage: "Hamárosan kap megerősítést e-mailben és WhatsAppon",
        orderId: "Rendelésszám",
        backToSite: "Vissza a weboldalra",
        stockAlert: "Elérte a maximális mennyiséget",
        cartEmptyAlert: "A kosár üres",
        orderError: "Hiba történt. Próbálja újra.",
        orderSuccess: "Rendelés sikeresen elküldve!",
        loading: "Betöltés...",
        wishlist: "Kedvencek",
        wishlistAdded: "Hozzáadva a kedvencekhez",
        wishlistRemoved: "Eltávolítva a kedvencekből",
        footerTagline: "Gasztronómiai élmény a Nemzeti Park szívéből",
        footerShop: "Bolt",
        footerCompany: "Cég",
        footerSupport: "Támogatás",
        footerContact: "Kapcsolat",
        footerAbout: "Rólunk",
        footerTerms: "Általános Szerződési Feltételek",
        footerPrivacy: "Adatvédelmi Szabályzat",
        footerReturns: "Visszaküldés",
        footerShipping: "Szállítás",
        footerFAQ: "GYIK",
        footerCopyright: "© 2026 Gruppo Gizzi. Minden jog fenntartva.",
        footerPhone: "+39 335 806 0715",
        footerEmail: "info@gruppogizzi.it",
        footerAddress: "Cilento, Olaszország",
        gdprTitle: "Adatvédelem és Cookie Irányelvek",
        gdprText: "Sütiket és hasonló technológiákat használunk a böngészési élmény javítására, a forgalom elemzésére és a tartalmak és hirdetések személyre szabására. A folytatással elfogadja Cookie Irányelveinket.",
        accept: "Összes elfogadása",
        reject: "Elutasítás",
        toastSuccess: "Siker",
        toastError: "Hiba",
        toastWarning: "Figyelem",
        close: "Bezárás",
        menu: "Menü",
        open: "Megnyitás",
        themeLight: "Világos téma",
        themeDark: "Sötét téma",
        viewAll: "Összes megtekintése",
        readMore: "Tovább olvasás",
        showLess: "Kevesebb megjelenítése",
        next: "Következő",
        previous: "Előző",
        page: "Oldal",
        of: "/",
        results: "eredmény",
        noResults: "Nincs találat",
        sortBy: "Rendezés",
        sortByDefault: "Alapértelmezett",
        sortByPriceLow: "Ár: Növekvő",
        sortByPriceHigh: "Ár: Csökkenő",
        sortByNew: "Legújabb",
        sortByPopular: "Népszerű",
        filter: "Szűrő",
        filters: "Szűrők",
        clearFilters: "Szűrők törlése",
        applyFilters: "Szűrők alkalmazása",
        categoryAll: "Összes kategória",
        priceRange: "Ártartomány",
        rating: "Értékelés",
        brand: "Márka",
        size: "Méret",
        color: "Szín",
        material: "Anyag",
        availability: "Elérhetőség",
        available: "Elérhető",
        unavailable: "Nem elérhető",
        onSale: "Akciós",
        newArrivals: "Újdonságok",
        bestSellers: "Legjobban fogyó",
        recommended: "Ajánlott",
        relatedProducts: "Kapcsolódó termékek",
        youMayAlsoLike: "Ez is tetszhet",
        recentlyViewed: "Nemrég megtekintett",
        compare: "Összehasonlítás",
        compareProducts: "Termékek összehasonlítása",
        removeCompare: "Eltávolítás az összehasonlításból",
        maxCompareReached: "Legfeljebb 4 terméket hasonlíthat össze",
        share: "Megosztás",
        shareOnFacebook: "Megosztás Facebookon",
        shareOnTwitter: "Megosztás Twitteren",
        shareOnWhatsApp: "Megosztás WhatsAppon",
        copyLink: "Link másolása",
        linkCopied: "Link a vágólapra másolva",
        reportProduct: "Termék jelentése",
        reportSuccess: "Termék sikeresen jelentve",
        askQuestion: "Kérdés feltevése",
        submitQuestion: "Kérdés beküldése",
        questionSuccess: "Kérdés sikeresen elküldve",
        productReviews: "Termékértékelések",
        writeReview: "Értékelés írása",
        reviewTitle: "Cím",
        reviewContent: "Értékelése",
        ratingRequired: "Értékelés szükséges",
        reviewSuccess: "Értékelés sikeresen elküldve",
        verifiedPurchase: "Ellenőrzött vásárlás",
        helpful: "Hasznos",
        notHelpful: "Nem hasznos",
        reportReview: "Értékelés jelentése",
        cart: "Kosár",
        sectionFeature1Title: "100% Természetes",
        sectionFeature1Desc: "Hiteles termékek tartósítószerek és mesterséges adalékok nélkül",
        sectionFeature2Title: "Cilento Származás",
        sectionFeature2Desc: "A Nemzeti Park szívétől közvetlenül az Ön otthonába",
        sectionFeature3Title: "Prémium Minőség",
        sectionFeature3Desc: "A legjobb helyi termékek gondos kiválasztása"
    }
};